service: insecure-svc

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    DB_PASSWORD: "hardcoded-secret-123"
    AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "*"
          Resource: "*"

functions:
  vulnerable:
    handler: handler.run
    events:
      - http:
          path: run
          method: post
